// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {debt} from '../models';

export function DeleteDebtItem(arg1:string):Promise<void>;

export function GetDebt():Promise<Array<debt.DebtItem>>;

export function GetTotalDebtAmount():Promise<number>;

export function GetTotalMonthlyDebtAmount():Promise<number>;

export function SubmitDebtItem(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function UpdateDebtItem(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;
