// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteDebtItem(arg1) {
  return window['go']['debt']['Debt']['DeleteDebtItem'](arg1);
}

export function GetDebt() {
  return window['go']['debt']['Debt']['GetDebt']();
}

export function GetTotalDebtAmount() {
  return window['go']['debt']['Debt']['GetTotalDebtAmount']();
}

export function GetTotalMonthlyDebtAmount() {
  return window['go']['debt']['Debt']['GetTotalMonthlyDebtAmount']();
}

export function SubmitDebtItem(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['debt']['Debt']['SubmitDebtItem'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateDebtItem(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['debt']['Debt']['UpdateDebtItem'](arg1, arg2, arg3, arg4, arg5);
}
